wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.15
    is_jupyter_run: true
    python_version: 3.6.8
batch_size:
  desc: null
  value: 321.9792009087659
epochs:
  desc: null
  value: 467.3651566477609
learning_rate:
  desc: null
  value: 0.8466647727385208
